## 13/04/2020 The Basics of NumPy Arrays

### NumPy Array Attributes

Each array has attributes ndim (number of dimensions), shape (the size of each dimension), and size (total size of the array).

In [1]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [2]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


Dtype attribute shows the data type of the array.

In [4]:
print("dtype:", x3.dtype)

dtype: int32


Also itemsize (size of each array element in bytes), and nbytes (total size of array in bytes).

In [5]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 240 bytes


### Array Indexing: Accessing Single Elements

The ith value can be accessed by specifying the index in square brackets, starting from 0.

In [6]:
x1

array([5, 0, 3, 3, 7, 9])

In [7]:
x1[0]

5

In [8]:
x1[-1]

9

For multidimensional arrays items can be accessed using a tuple of indices:

In [9]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [10]:
x2[0,0]

3

In [11]:
x2[2,0]

1

Can modify arrays using method below:

In [12]:
x2[0,0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

### Array Slicing: Accessing Subarrays

Notation to access subarrays:   
x\[start:stop:step\]
If any of these are unspecified they default to:   
start=0, stop=size of dimension, step=1.

In [13]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
x[:5] # first five elements

array([0, 1, 2, 3, 4])

In [15]:
x[5:] # elements after index 5

array([5, 6, 7, 8, 9])

In [16]:
x[4:7]

array([4, 5, 6])

In [17]:
x[::2] # Every other element

array([0, 2, 4, 6, 8])

In [18]:
x[1::2] # Every other element, starting at index 1

array([1, 3, 5, 7, 9])

Step value can be negative. In this case, the defaults for start and stop are swapped. This becomes a way to reverse an array.

In [19]:
x[::-1] # All elements reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [20]:
x[5::-2] # Reversed every other from index 5

array([5, 3, 1])

__Multidimensional subarrays__

Multiple slices sperated by commas, x\[rows slice, columns slice\]


In [21]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [22]:
x2[:2, :3] # Two rows (0,1) and three columns (0,1,2)

array([[12,  5,  2],
       [ 7,  6,  8]])

In [23]:
x2[:3, ::2] # All rows, every other column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

Subarray dimensions can me reversed:

In [24]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

__Accessing arrays rows and columns__   
A single column or row can be accessed by combinging indexing and slicing, using an empty slice marked by a single colon:

In [25]:
print(x2[:, 0]) #First column of x2

[12  7  1]


In [26]:
print(x2[0, :]) #First row of x2

[12  5  2  4]


In [27]:
print(x2[0]) # Equivalent to x2[0, :]

[12  5  2  4]


__Subarrays as no copy views__   
One important–and extremely useful–thing to know about array slices is that they return views rather than copies of the array data.

In [28]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [29]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [31]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [32]:
print (x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


The original array is also modified.

__Creating copies of arrays__   
Copies of arrays can be created using the copy() method:

In [33]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [34]:
x2_sub_copy[0,0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


The original array remains unchanged.

In [35]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


### Reshaping of arrays

The reshape method can be used to reshape arrays. For example arranging numbers 1-9 into a 3x3 grid.

In [37]:
grid = np.arange(1, 10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


The size of the initial array must match the size of the reshaped array.   
Another use is the reshaping of a 1 dimensional array into a row or column matrix. Can be done with the reshape method or the newaxis keyword in a slice operation.

In [40]:
x = np.array([1,2,3])

# row vector via reshape
x.reshape((1,3))

array([[1, 2, 3]])

In [41]:
# row vector via newaxis

x[np.newaxis, :]

array([[1, 2, 3]])

In [42]:
# column vector via reshape
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [43]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

### Array Concatenation and Splitting

__Concatenation of arrays__   
Concatenation of two arrays is primarily accomplished by using np.concatenate, np.vstack and np.hstack.   
np.concatenate takes a tuple or list of arrays as its first argument:

In [44]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

Can concatenate more than two arrays at once:

In [45]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


Can concatenate 2-dim arrays:

In [47]:
grid = np.array([[1, 2, 3], [4, 5, 6]])

In [48]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [49]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

np.vstack(vertical stack) and np.hstack(horizontal stack):

In [51]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [52]:
# horizontally stack
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

np.dstack stacks along the third axis.

__Splitting of arrays__   
Implemented with np.split, np.hsplit, np.vsplit. For each we pass a list of indices giving the split points:

In [53]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3,5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


N split points leads to N+1 subarrays.

In [58]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [59]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [60]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


## Computation on NumPy Arrays: Universal Functions

Lookping in CPython is suprisingly slow. For example to find the reciprical via loops:

In [1]:
import numpy as np
np.random.seed(0) # Seeding random numbers

# define a function to calculate reciprocals

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

# Create array of random values
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [4]:
# for an array of size 1 million
big_array = np.random.randint(1, 100, size=1000000)

%timeit compute_reciprocals(big_array)

3.97 s ± 618 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### Introducing UFuncs

These are _vectorized_ operations.This can be accomplished by simply performing an operation on the array, which will then be applied to each element. The vectorized approach is designed to push the loop into the compiled layer that underlies NumPy, leading to faster execution.

In [5]:
print(compute_reciprocals(values))
print( 1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


Comparing to the loop:

In [6]:
%timeit (1.0 / big_array)

9.15 ms ± 924 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


We can also operate between two arrays:

In [8]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

ufuncs can also operate on multi-dimensional arrays:

In [9]:
x = np.arange(9).reshape((3, 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

## Exploring NumPy's UFuncs

NumPy;s ufuncs make use of Python's native arithmetic operators:

In [10]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


Can also use ufuncs for negation, exponentiation and modulus:

In [11]:
print("-x     =", -x)
print("x ** 2 =", x ** 2)
print("x % 2  =", x % 2)

-x     = [ 0 -1 -2 -3]
x ** 2 = [0 1 4 9]
x % 2  = [0 1 0 1]


These can be stung together:

In [12]:
-(0.5 * x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

__Absolute Value__

In [13]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [14]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [15]:
np.abs(x)

array([2, 1, 0, 1, 2])

The absolute ufunc can handle complex values, returning the magnitude:

In [16]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

__Trigonometric functions__   
Start by defining an array of angles:

In [18]:
theta = np.linspace(0, np.pi, 3)

In [19]:
print("theta      =", theta)
print("sin(theta) =", np.sin(theta))
print("cos(theta) =", np.cos(theta))
print("tan(theta) =", np.tan(theta))

theta      = [0.         1.57079633 3.14159265]
sin(theta) = [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) = [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) = [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


Can also compute the inverse trig functions:

In [20]:
x = [-1, 0, 1]
print("x         =", x)
print("arcsin(x) =", np.arcsin(x))
print("arccos(x) =", np.arccos(x))
print("arctan(x) =", np.arctan(x))

x         = [-1, 0, 1]
arcsin(x) = [-1.57079633  0.          1.57079633]
arccos(x) = [3.14159265 1.57079633 0.        ]
arctan(x) = [-0.78539816  0.          0.78539816]


__Exponentials and logarithms__

In [21]:
x = [1, 2, 3]
print("x    =", x)
print("e^x  =", np.exp(x))
print("2^x  =", np.exp2(x))
print("3^x  =", np.power(3, x))

x    = [1, 2, 3]
e^x  = [ 2.71828183  7.3890561  20.08553692]
2^x  = [2. 4. 8.]
3^x  = [ 3  9 27]


In [22]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


To maintain precision with very small input:

In [23]:
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


When x is very small, these functions give more precise values than if the raw np.log or np.exp were to be used.

__Specialized ufuncs__

NumPy has many more ufuncs available, including hyperbolic trig functions, bitwise arithmetic, comparison operators, conversions from radians to degrees, rounding and remainders, and much more. A look through the NumPy documentation reveals a lot of interesting functionality.

Another excellent source for more specialized and obscure ufuncs is the submodule scipy.special. If you want to compute some obscure mathematical function on your data, chances are it is implemented in scipy.special. There are far too many functions to list them all, but the following snippet shows a couple that might come up in a statistics context:

In [25]:
from scipy import special

In [26]:
# Gamma functions (generalized factorials) and related functions
x = [1, 5, 10]
print("gamma(x)     =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2)   =", special.beta(x, 2))

gamma(x)     = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x, 2)   = [0.5        0.03333333 0.00909091]


In [27]:
# Error function (integral of Gaussian)
# its complement, and its inverse
x = np.array([0, 0.3, 0.7, 1.0])
print("erf(x)  =", special.erf(x))
print("erfc(x) =", special.erfc(x))
print("erfinv(x) =", special.erfinv(x))

erf(x)  = [0.         0.32862676 0.67780119 0.84270079]
erfc(x) = [1.         0.67137324 0.32219881 0.15729921]
erfinv(x) = [0.         0.27246271 0.73286908        inf]


__Specifying output__

For large calculations, it is sometimes useful to be able to specify the array where the result of the calculation will be stored. Rather than creating a temporary array, this can be used to write computation results directly to the memory location where you'd like them to be. For all ufuncs, this can be done using the out argument of the function:

In [28]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [29]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


If we had instead written y[::2] = 2 ** x, this would have resulted in the creation of a temporary array to hold the results of 2 ** x, followed by a second operation copying those values into the y array. This doesn't make much of a difference for such a small computation, but for very large arrays the memory savings from careful use of the out argument can be significant.

__Aggregates__   
For binary ufuncs, there are some interesting aggregates. For example, if we'd like to reduce an array with a particular operation, we can use the reduce method of any ufunc. A reduce repeatedly applies a given operation to the elements of an array until only a single result remains.

For example, called reduce on the add ufinc returns the sum of all elements in the array:

In [30]:
x = np.arange(1, 6)
np.add.reduce(x)

15

To obtain the product:

In [31]:
np.multiply.reduce(x)

120

To store all the intermediate results of the computation, we can instead use accumulate:

In [32]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [33]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120], dtype=int32)

__Outer products__

Any ufunc can compute the output of all the pairs of two different inputs using the outer method, This allows for creating a mutiplication table in one line:

In [34]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])